// Build: posts/*.md → static HTML pages + lib/notes.gen.ts (bundled into the worker).
// `node build.mjs --keygen` creates the actor keypair once.
import { createHash, generateKeyPairSync } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync, appendFileSync } from "node:fs";

const site = JSON.parse(readFileSync("site.config.json", "utf8"));
const BASE = site.url.replace(/\/$/, "");
const HOST = new URL(BASE).host;
const HANDLE = `@${site.username}@${HOST}`;

if (process.argv.includes("--keygen")) {
  if (existsSync("public.pem")) throw new Error("public.pem exists; delete it (and AP_PRIVATE_KEY) to rotate");
  const { publicKey, privateKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
  writeFileSync("public.pem", publicKey.export({ type: "spki", format: "pem" }));
  const der = privateKey.export({ type: "pkcs8", format: "der" }).toString("base64");
  appendFileSync(".env.server", `AP_PRIVATE_KEY=${der}\n`, { mode: 0o600 });
  console.log("wrote public.pem and AP_PRIVATE_KEY in .env.server");
  process.exit(0);
}

// ---------- tiny markdown ----------

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function inline(s) {
  const links = [];
  const hold = (html) => `\u0000${links.push(html) - 1}\u0000`;
  s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, (_, t, u) => hold(`<a href="${esc(u)}">${esc(t)}</a>`));
  s = s.replace(/https?:\/\/[^\s<]+[^\s<.,;:!?)]/g, (u) => hold(`<a href="${esc(u)}">${esc(u.replace(/^https?:\/\//, ""))}</a>`));
  s = s.replace(/`([^`]+)`/g, (_, c) => hold(`<code>${esc(c)}</code>`));
  s = esc(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>");
  return s.replace(/\u0000(\d+)\u0000/g, (_, i) => links[i]);
}

const render = (md) =>
  md.trim().split(/\n\s*\n/).map((p) => `<p>${p.split("\n").map(inline).join("<br>")}</p>`).join("");

// ---------- read posts ----------

const TYPES = { gif: "image/gif", png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", webp: "image/webp" };
const mediaType = (u) => TYPES[u.split(".").pop().toLowerCase()] ?? "application/octet-stream";

const notes = readdirSync("posts")
  .filter((f) => f.endsWith(".md"))
  .map((f) => {
    const raw = readFileSync(`posts/${f}`, "utf8");
    const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
    if (!m) throw new Error(`${f}: missing front matter`);
    const meta = Object.fromEntries(m[1].split("\n").map((l) => l.split(/:\s*(.*)/s).slice(0, 2)));
    if (!meta.date) throw new Error(`${f}: missing date`);
    const html = render(m[2]);
    const note = {
      id: f.replace(/\.md$/, ""),
      published: new Date(meta.date).toISOString(),
      ...(meta.updated ? { updated: new Date(meta.updated).toISOString() } : {}),
      html,
      ...(meta.image ? { image: { url: meta.image, alt: meta.alt ?? "", mediaType: mediaType(meta.image) } } : {}),
    };
    if (note.image && !existsSync(`.${note.image.url}`)) throw new Error(`${f}: missing ${note.image.url}`);
    note.hash = createHash("sha256").update(html + (note.updated ?? "") + (note.image ? JSON.stringify(note.image) : "")).digest("hex");
    return note;
  })
  .sort((a, b) => b.published.localeCompare(a.published));

if (!existsSync("public.pem")) throw new Error("no public.pem: run `node build.mjs --keygen` first");

writeFileSync(
  "lib/notes.gen.ts",
  `// Generated by build.mjs. Do not edit.
export type Note = { id: string; published: string; updated?: string; html: string; hash: string; image?: { url: string; alt: string; mediaType: string } };
export const SITE = ${JSON.stringify(site, null, 2)} as { url: string; username: string; name: string; summary: string; published: string; icon?: string };
export const PUBLIC_KEY_PEM = ${JSON.stringify(readFileSync("public.pem", "utf8"))};
export const NOTES: Note[] = ${JSON.stringify(notes, null, 2)};
`,
);

// ---------- pages ----------

const fmt = (iso) => new Date(iso).toLocaleString("en-AU", { dateStyle: "medium", timeStyle: "short", timeZone: site.timeZone ?? "UTC" });

const page = ({ title, alternate, body }) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<link rel="alternate" type="application/activity+json" href="${alternate}">
<link rel="stylesheet" href="/style.css">
</head>
<body>
<header class="me">
  <a class="name" href="/">${esc(site.name)}</a>
  <button class="handle" type="button" title="Copy handle" data-copy="${HANDLE}">${HANDLE}</button>
</header>
<main>
${body}
</main>
<footer>Follow ${HANDLE} from Mastodon or any Fediverse app. Static HTML on Spacefast, plus a small ActivityPub worker.</footer>
<script>
document.querySelectorAll("[data-copy]").forEach((b) => b.onclick = async () => {
  try { await navigator.clipboard.writeText(b.dataset.copy); b.classList.add("copied"); setTimeout(() => b.classList.remove("copied"), 1200); } catch {}
});
</script>
</body>
</html>
`;

const card = (n, link) => `<article class="note">
  <div class="body">${n.html}</div>
  ${n.image ? `<img class="media" src="${esc(n.image.url)}" alt="${esc(n.image.alt)}" loading="lazy">` : ""}
  <a class="meta" href="/notes/${n.id}/"${link ? "" : ' aria-current="page"'}><time datetime="${n.published}">${fmt(n.published)}</time>${n.updated ? " · edited" : ""}</a>
</article>`;

rmSync("notes", { recursive: true, force: true });
for (const n of notes) {
  mkdirSync(`notes/${n.id}`, { recursive: true });
  const title = n.html.replace(/<[^>]+>/g, "").slice(0, 60);
  writeFileSync(
    `notes/${n.id}/index.html`,
    page({
      title: `${title} · ${site.name}`,
      alternate: `${BASE}/ap/notes/${n.id}`,
      body: `${card(n, false)}
<section class="reactions" data-note="${n.id}" hidden>
  <p class="counts"></p>
  <ol class="replies"></ol>
</section>
<script>
(async () => {
  const el = document.querySelector(".reactions");
  const r = await fetch("/ap/interactions/" + el.dataset.note).then((r) => r.ok ? r.json() : null).catch(() => null);
  if (!r || (!r.likes && !r.boosts && !r.replies.length)) return;
  const plural = (n, w) => n + " " + w + (n === 1 ? "" : "s");
  el.querySelector(".counts").textContent = [plural(r.likes, "like"), plural(r.boosts, "boost"), plural(r.replies.length, "reply").replace("replys", "replies")].join(" · ");
  const ol = el.querySelector(".replies");
  for (const x of r.replies) {
    const li = document.createElement("li");
    const a = Object.assign(document.createElement("a"), { href: x.url, textContent: x.handle });
    const p = document.createElement("p");
    p.textContent = new DOMParser().parseFromString(x.content, "text/html").body.textContent;
    li.append(a, p);
    ol.append(li);
  }
  el.hidden = false;
})();
</script>`,
    }),
  );
}

writeFileSync(
  "index.html",
  page({
    title: site.name,
    alternate: `${BASE}/ap/actor`,
    body: `<p class="summary">${esc(site.summary)}</p>
${notes.map((n) => card(n, true)).join("\n")}`,
  }),
);

console.log(`built ${notes.length} notes for ${HANDLE}`);
